export const FETCH_POST = "FETCH_DETAIL_OF_ONE_POST";
export const FETCH_POST_SUCCESSED = "FETCH_POST_SUCCESSED";
export const FETCH_POST_FAILED = "FETCH_POST_FAILED";

export const CLEAR_POST_DETAIL = "CLEAR_POST_DETAIL";

export const FETCH_POSTS = "FETCH_ALL_THE_POSTS_FROM_SERVER";
export const FETCH_POSTS_SUCCESSED = "FETCH_ALL_THE_POSTS_FROM_SERVER_SUCCESSED";
export const FETCH_POSTS_FAILED = "FETCH_ALL_THE_POSTS_FROM_SERVER_FAILED";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const OPEN_SEARCH_BOX = "OPEN_SEARCH_BOX";
export const CLOSE_SEARCH_BOX = "CLOSE_SEARCH_BOX";
export const SEARCH_POSTS_BY_KEYWORD = "SEARCH_POSTS_BY_KEYWORD";
export const SEARCH_POSTS_BY_KEYWORD_SUCCESS = "SEARCH_POSTS_BY_KEYWORD_SUCCESS";
export const SEARCH_POSTS_BY_KEYWORD_FAILED = "SEARCH_POSTS_BY_KEYWORD_FAILED";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_SUCCESSED = "GET_ALL_CATEGORIES_SUCCESSED";
export const GET_ALL_CATEGORIES_FAILED = "GET_ALL_CATEGORIES_FAILED";

export const OPEN_LOGIN_BOX = "OPEN_LOGIN_BOX";
export const CLOSE_LOGIN_BOX = "CLOSE_LOGIN_BOX";

export const PENDING_LOGIN = "PENDING_LOGIN";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESSED = "LOGIN_SUCCESSED";
