export const FETCH_POST = "FETCH_DETAIL_OF_ONE_POST";
export const FETCH_POST_SUCCESSED = "FETCH_POST_SUCCESSED";
export const FETCH_POST_FAILED = "FETCH_POST_FAILED";

export const FETCH_POSTS = "FETCH_ALL_THE_POSTS_FROM_SERVER";
export const FETCH_POSTS_SUCCESSED = "FETCH_ALL_THE_POSTS_FROM_SERVER_SUCCESSED";
export const FETCH_POSTS_FAILED = "FETCH_ALL_THE_POSTS_FROM_SERVER_FAILED";
